---
- name: Laboratorio Docker
  hosts: docker
  gather_facts: yes

  tasks:

    - name: Mostrar nombre del host
      debug:
        msg: "{{ ansible_hostname }}"

    - name: Mostrar sistema operativo
      debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Crear directorio principal
      file:
        path: /tmp/ansible-demo
        state: directory

    - name: Crear archivo info.txt
      copy:
        dest: /tmp/ansible-demo/info.txt
        content: |
          Servidor: {{ ansible_hostname }}
          Sistema Operativo: {{ ansible_distribution }}

    - name: Crear directorios
      file:
        path: "/tmp/ansible-demo/{{ item }}"
        state: directory
      loop:
        - logs
        - backup
        - config

    - name: Mostrar mensaje solo si es Ubuntu
      debug:
        msg: "Este servidor ejecuta Ubuntu."
      when: ansible_distribution == "Ubuntu"